[package]
name = "remotion-renderer-rs"
description = "Remotion Renderer, now in Rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
license = "MIT"
authors = ["Siddharth Jha"]
readme = "README.md"
keywords = ["remotion"]
categories = []
build = "build.rs"

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
wry = "0.33.0"
swift-bridge = "0.1"


[target.'cfg(windows)'.dependencies]
webview2-com = "0.26.0"
